Add digasId for shows
Studentmediene/RadioRevolt-API pull request #16
Opened 2017-02-02 17:58 UTC by Santiario

2017-02-05 20:06 UTC, essoen requested changes

2017-02-05 20:06 UTC, essoen commented on src/models/show.model.js
> +        digasId: { // For use with LDAP
Does this have anything to do with LDAP?
Aren't we switching to AD?

2017-02-05 20:09 UTC, Santiario commented on src/models/show.model.js
> +        digasId: { // For use with LDAP
Nothing to do with LDAP, "Digas" is the program used by radio journalists to manage the archive of podcasts and ondemand streams.

2017-02-05 20:35 UTC, essoen commented on src/models/show.model.js
> +        digasId: { // For use with LDAP
Then why the comment:
> // For use with LDAP
? =)

2017-02-05 20:38 UTC, Santiario commented on src/models/show.model.js
> +        digasId: { // For use with LDAP
Opps, too much copy paste

2017-02-12 16:23 UTC, essoen approved these changes

2017-02-12 16:23 UTC, merged